### ISSUE TITLE
Does retry mechanism work properly?

### ISSUE THREAD

**Issue by andrew00x** [Aiven-Open/opensearch-connector-for-apache-kafka#179]
Retry mechanism doesn't work properly, in my opinion. Is it intentional behaviour to check exact matching between expected exception and actual exception [here](https://github.com/aiven/opensearch-connector-for-apache-kafka/blob/main/src/main/java/io/aiven/kafka/connect/opensearch/RetryUtil.java#L121) , shouldn't it be `repeatableException.isAssignableFrom(e.getClass())`? Retry works pretty rarely, almost never, I would say. In the case that I've met [BulkProcessor](https://github.com/aiven/opensearch-connector-for-apache-kafka/blob/main/src/main/java/io/aiven/kafka/connect/opensearch/BulkProcessor.java#L401) doesn't work well.
This [line](https://github.com/aiven/opensearch-connector-for-apache-kafka/blob/main/src/main/java/io/aiven/kafka/connect/opensearch/RetryUtil.java#L105) doesn't look right either, throwing `Exception` is not common and recommended practice, should it be expected to be thrown ever?

**Comment by miguelskeeled** [comment]
Hi, we are currently facing a similar problem. Our connector sometimes fails with a ConnectionException, however, in the error trace, we see that the connector only attempted to process 1 time.

The error trace:
`
 "trace": "org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:614)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: org.apache.kafka.connect.errors.ConnectException: Failed to bulk processing after total of 1 attempt(s)\n\tat io.aiven.kafka.connect.opensearch.RetryUtil.callWithRetry(RetryUtil.java:137)\n\tat io.aiven.kafka.connect.opensearch.BulkProcessor$BulkTask.execute(BulkProcessor.java:367)\n\tat io.aiven.kafka.connect.opensearch.BulkProcessor$BulkTask.call(BulkProcessor.java:356)\n\tat io.aiven.kafka.connect.opensearch.BulkProcessor$BulkTask.call(BulkProcessor.java:337)\n\t... 4 more\nCaused by: org.apache.kafka.connect.errors.ConnectException: org.apache.http.ConnectionClosedException: Connection is closed\n\tat io.aiven.kafka.connect.opensearch.BulkProcessor$BulkTask.lambda$execute$0(BulkProcessor.java:399)\n\tat io.aiven.kafka.connect.opensearch.RetryUtil.callWithRetry(RetryUtil.java:119)\n\t... 7 more\nCaused by: org.apache.http.ConnectionClosedException: Connection is closed\n\tat org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:941)\n\tat org.opensearch.client.RestClient.performRequest(RestClient.java:332)\n\tat org.opensearch.client.RestClient.performRequest(RestClient.java:320)\n\tat org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1911)\n\tat org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1877)\n\tat org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1845)\n\tat org.opensearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:364)\n\tat io.aiven.kafka.connect.opensearch.BulkProcessor$BulkTask.lambda$execute$0(BulkProcessor.java:370)\n\t... 8 more\nCaused by: org.apache.http.ConnectionClosedException: Connection is closed\n\tat org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:356)\n\tat org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261)\n\tat org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87)\n\tat org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40)\n\tat org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)\n\tat org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)\n\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)\n\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)\n\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)\n\tat org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)\n\tat org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)\n\t... 1 more\n"
`

Our connector config has a `max.retries = 5` and a `connection.timeout.ms = 5000` however, once the connection fails, it never retries.

Our theory is that this exception is not matching the condition of retry util function. 

If this is expected, is there any workaround?

**Comment by andrew00x** [comment]
Hi @miguelskeeled,
Our problem is exactly the same, connection errors are not retryable. I don't think that there is some workaround, retry works only if `RuntimeException` occurs. It looks like a bug to me, unless I'm missing something. Connection error should be the very first candidate for retry, I think.
I don't think checking the exception class is a good approach, some `Predicate` would work better. But let's wait for the authors' answers, maybe it was done for some reason.

**Comment by edjannoo** [comment]
Hi @willyborankin 
We've encountered the same issue too. In our case, OpenSearch sometimes returns a `429 Too Many Requests` status code which results in an `OpenSearchStatusException`. As that isn't the `RuntimeException` class, `callWithRetry` doesn't retry the request and instead the task is killed. We've also observed it when the connection is closed or the socket times out.
All of these are circumstances under which I would expect a retry to occur.
Is there any update on this issue you can share?

**Comment by kandji-alex** [comment]
Is there no way this could be released in a 2.0 branch as well, or at least make the 3.0 branch compatible with OS 2?

**Comment by willyborankin** [comment]
> Is there no way this could be released in a 2.0 branch as well, or at least make the 3.0 branch compatible with OS 2?

it is compatible with OS 2.x. The versioning for the connector not the same as for OS plugins.
